### PR TITLE
Add UniLWP.Droid

### PR DESCRIPTION
**Pull request by JustinFincher**
This is a pull request for adding UniLWP.Droid upm package ([Repo Link](https://github.com/JustinFincher/UniLWP.Droid.Package.Free)).   

FYI: UniLWP.Droid is an Android plugin that replaces the default Activity implementation in the Unity jar file with a customized Activity subclass that supports switching Surface from and to WallpaperServices.

Files changed:
```
README.md
```

### CODE REVIEW

**Comment by starikcetin** [comment]
Can you add a clarification about this being a limited free version in the description column?

(Free version) or (Limited version) at the end would do.

**Comment by JustinFincher** [comment]
Sure, will do. :-D

**Comment by JustinFincher** [comment]
I have pushed another commit https://github.com/starikcetin/awesome-upm/pull/42/commits/e416b08137b79eea4e0a3ae22847ecc6bb40ec25 with (Limited version) added at the end of the description, sorry for the previous commit where I was not clear about that. If you want me to squash two commits into one, please let me know!

**Comment by starikcetin** [comment]
Thank you!

**Pull request merged**
